### ISSUE TITLE
1.0.3 DEB crashes on launch

### ISSUE THREAD

**Issue by AnalogMan151** [arslan2012/CattleGrid#1]
1.0.3 update crashes on Jailbroken iPhone XR 13.5. Update 1.0.2 still works fine.

**Comment by arslan2012** [comment]
if it crashed, post cr4shed log

**Comment by AnalogMan151** [comment]
Instructions appear to be missing. Please provide process to acquire cr4shed log.

**Comment by arslan2012** [comment]
cr4shed is an app available on Packix repo that records crash logs

**Comment by AnalogMan151** [comment]
[1.0.3 Cattlegrid.txt](https://github.com/arslan2012/CattleGrid/files/4699048/1.0.3.Cattlegrid.txt)

**Comment by arslan2012** [comment]
it looks like a NPE but didn't tell me where it happened.

whats in your /var/mobile/tagbin folder?is it created? is it empty?

**Comment by AnalogMan151** [comment]
There was no tagbin folder but when I made one the app started working.

**Comment by arslan2012** [comment]
OK thanks, I'll try to make the app create the folder on installation next version

**Comment by arslan2012** [comment]
ok drafted a new release
